name: Daily refresh

on:
  schedule:
    - cron: "15 20 * * *"   # 20:15 UTC daily (≈ 06:15 AEST)
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # IMPORTANT: allows the job to commit JSON back to the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install            # npm ci can fail if package-lock.json doesn't exist

      - name: Run scraper
        run: npm run scrape

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: daily listings refresh"
            git push
          else
            echo "No changes."
          fi

